import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import { Header } from 'next/dist/lib/load-custom-routes'
import { UserProvider } from './userContext'


const inter = Inter({ subsets: ['latin'] })

 const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="es">
        <body className='w-full min-h-screen bg-[#FFFCE6]  font-Cinzel'>{children}</body>
      </html>
    </UserProvider>
  )
}
